# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InicioSubirDatos.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(508, 447)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(160, 20, 171, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(250, 100, 211, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayoutTablaMostrarDatos = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayoutTablaMostrarDatos.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutTablaMostrarDatos.setObjectName("horizontalLayoutTablaMostrarDatos")
        self.tableViewMostrarArchivosSeleccionados = QtWidgets.QTableView(self.horizontalLayoutWidget)
        self.tableViewMostrarArchivosSeleccionados.setObjectName("tableViewMostrarArchivosSeleccionados")
        self.horizontalLayoutTablaMostrarDatos.addWidget(self.tableViewMostrarArchivosSeleccionados)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(70, 120, 111, 100))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.AnadirverticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.AnadirverticalLayout.setContentsMargins(0, 0, 0, 0)
        self.AnadirverticalLayout.setObjectName("AnadirverticalLayout")
        self.pushButtonAnadirArchivo = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButtonAnadirArchivo.setObjectName("pushButtonAnadirArchivo")
        self.AnadirverticalLayout.addWidget(self.pushButtonAnadirArchivo)
        self.pushButtonEliminar = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButtonEliminar.setObjectName("pushButtonEliminar")
        self.AnadirverticalLayout.addWidget(self.pushButtonEliminar)
        self.pushButtonCargarDatos = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButtonCargarDatos.setObjectName("pushButtonCargarDatos")
        self.AnadirverticalLayout.addWidget(self.pushButtonCargarDatos)
        self.labelTtiulo = QtWidgets.QLabel(self.centralwidget)
        self.labelTtiulo.setGeometry(QtCore.QRect(180, 20, 169, 39))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.labelTtiulo.setFont(font)
        self.labelTtiulo.setObjectName("labelTtiulo")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(270, 340, 161, 30))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayoutVerDatos = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayoutVerDatos.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayoutVerDatos.setObjectName("horizontalLayoutVerDatos")
        self.pushButtonMostrarDatos = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonMostrarDatos.setObjectName("pushButtonMostrarDatos")
        self.horizontalLayoutVerDatos.addWidget(self.pushButtonMostrarDatos)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 508, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbrir = QtWidgets.QAction(MainWindow)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionNueva_Ventana = QtWidgets.QAction(MainWindow)
        self.actionNueva_Ventana.setObjectName("actionNueva_Ventana")
        self.actionGuardar = QtWidgets.QAction(MainWindow)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_Como = QtWidgets.QAction(MainWindow)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionNueva_Ventana)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonAnadirArchivo.setText(_translate("MainWindow", "Añadir Archivo"))
        self.pushButtonEliminar.setText(_translate("MainWindow", "Eliminar Archivo"))
        self.pushButtonCargarDatos.setText(_translate("MainWindow", "Cargar Datos"))
        self.labelTtiulo.setText(_translate("MainWindow", "Bienvenidos "))
        self.pushButtonMostrarDatos.setText(_translate("MainWindow", "Ver Datos "))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo"))
        self.actionAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionNueva_Ventana.setText(_translate("MainWindow", "Nueva Ventana"))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar"))
        self.actionGuardar_Como.setText(_translate("MainWindow", "Guardar Como "))
        self.actionSalir.setText(_translate("MainWindow", "Salir "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
