# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\InicioSubirDatos.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaInicioSubirDatos(object):
    def setupUi(self, VistaInicioSubirDatos):
        VistaInicioSubirDatos.setObjectName("vistaInicioSubirDatos")
        VistaInicioSubirDatos.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VistaInicioSubirDatos.sizePolicy().hasHeightForWidth())
        VistaInicioSubirDatos.setSizePolicy(sizePolicy)
        VistaInicioSubirDatos.setMinimumSize(QtCore.QSize(1280, 720))
        VistaInicioSubirDatos.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(85, 125, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(VistaInicioSubirDatos)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 4, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 5, 1, 1, QtCore.Qt.AlignHCenter)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonCargarDatos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonCargarDatos.setFont(font)
        self.pushButtonCargarDatos.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.517413 rgba(55, 117, 206, 229), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Recursos/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonCargarDatos.setIcon(icon)
        self.pushButtonCargarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonCargarDatos.setObjectName("pushButtonCargarDatos")
        self.gridLayout.addWidget(self.pushButtonCargarDatos, 2, 2, 1, 1)
        self.pushButtonEliminar = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonEliminar.setFont(font)
        self.pushButtonEliminar.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.517413 rgba(55, 117, 206, 229), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Recursos/icons8-eliminar-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonEliminar.setIcon(icon1)
        self.pushButtonEliminar.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonEliminar.setObjectName("pushButtonEliminar")
        self.gridLayout.addWidget(self.pushButtonEliminar, 2, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 23, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setMaximumSize(QtCore.QSize(167777, 167777))
        self.label_2.setStyleSheet("image: url(:/newPrefix/Logo.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 23, 4, 1, 1)
        self.pushButtonAnadirArchivo = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonAnadirArchivo.setMaximumSize(QtCore.QSize(16777215, 48))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonAnadirArchivo.setFont(font)
        self.pushButtonAnadirArchivo.setStyleSheet("background-color: rgb(85, 170, 255);\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Recursos/icons8-añadir-libro-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAnadirArchivo.setIcon(icon2)
        self.pushButtonAnadirArchivo.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonAnadirArchivo.setObjectName("pushButtonAnadirArchivo")
        self.gridLayout.addWidget(self.pushButtonAnadirArchivo, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 5, 1, 1)
        self.listWidgetListaArchivos = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.listWidgetListaArchivos.sizePolicy().hasHeightForWidth())
        self.listWidgetListaArchivos.setSizePolicy(sizePolicy)
        self.listWidgetListaArchivos.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);")
        self.listWidgetListaArchivos.setAutoScrollMargin(23)
        self.listWidgetListaArchivos.setObjectName("listWidgetListaArchivos")
        self.gridLayout.addWidget(self.listWidgetListaArchivos, 23, 0, 1, 4)
        self.pushButtonMostrarDatos = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonMostrarDatos.setMaximumSize(QtCore.QSize(16777215, 16777213))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonMostrarDatos.setFont(font)
        self.pushButtonMostrarDatos.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.517413 rgba(55, 117, 206, 229), stop:1 rgba(255, 255, 255, 255));\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Recursos/icons8-hand-box-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonMostrarDatos.setIcon(icon3)
        self.pushButtonMostrarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonMostrarDatos.setObjectName("pushButtonMostrarDatos")
        self.gridLayout.addWidget(self.pushButtonMostrarDatos, 25, 1, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2.addLayout(self.verticalLayout, 1, 5, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(36)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 3, 1, 1, QtCore.Qt.AlignHCenter)
        VistaInicioSubirDatos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VistaInicioSubirDatos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        VistaInicioSubirDatos.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VistaInicioSubirDatos)
        self.statusbar.setObjectName("statusbar")
        VistaInicioSubirDatos.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(VistaInicioSubirDatos)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setObjectName("toolBar")
        VistaInicioSubirDatos.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAbrir = QtWidgets.QAction(VistaInicioSubirDatos)
        self.actionAbrir.setObjectName("actionAbrir")
        self.actionNueva_Ventana = QtWidgets.QAction(VistaInicioSubirDatos)
        self.actionNueva_Ventana.setObjectName("actionNueva_Ventana")
        self.actionGuardar = QtWidgets.QAction(VistaInicioSubirDatos)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuardar_Como = QtWidgets.QAction(VistaInicioSubirDatos)
        self.actionGuardar_Como.setObjectName("actionGuardar_Como")
        self.actionSalir = QtWidgets.QAction(VistaInicioSubirDatos)
        self.actionSalir.setObjectName("actionSalir")
        self.menuArchivo.addAction(self.actionAbrir)
        self.menuArchivo.addAction(self.actionNueva_Ventana)
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionGuardar_Como)
        self.menuArchivo.addAction(self.actionSalir)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(VistaInicioSubirDatos)
        QtCore.QMetaObject.connectSlotsByName(VistaInicioSubirDatos)

    def retranslateUi(self, VistaInicioSubirDatos):
        _translate = QtCore.QCoreApplication.translate
        VistaInicioSubirDatos.setWindowTitle(_translate("VistaInicioSubirDatos", "MainWindow"))
        self.label_4.setText(_translate("VistaInicioSubirDatos", "SOFTWARE RAPTOR"))
        self.label_3.setText(_translate("VistaInicioSubirDatos", "LISTA DIRECTORIOS"))
        self.pushButtonCargarDatos.setText(_translate("VistaInicioSubirDatos", "Cargar Datos"))
        self.pushButtonEliminar.setWhatsThis(_translate("VistaInicioSubirDatos", "<html><head/><body><p><img src=\":/newPrefix/Iocom png.png\"/></p></body></html>"))
        self.pushButtonEliminar.setText(_translate("VistaInicioSubirDatos", "Eliminar Archivo"))
        self.pushButtonAnadirArchivo.setText(_translate("VistaInicioSubirDatos", "Añadir Archivos"))
        self.label.setText(_translate("VistaInicioSubirDatos", "<html><head/><body><p><img src=\":/Images/Iocom png.png\"/></p></body></html>"))
        self.pushButtonMostrarDatos.setText(_translate("VistaInicioSubirDatos", "Ver Datos"))
        self.label_5.setText(_translate("VistaInicioSubirDatos", "IOCOM.LTDA"))
        self.menuArchivo.setTitle(_translate("VistaInicioSubirDatos", "Archivo"))
        self.toolBar.setWindowTitle(_translate("VistaInicioSubirDatos", "toolBar"))
        self.actionAbrir.setText(_translate("VistaInicioSubirDatos", "Abrir"))
        self.actionNueva_Ventana.setText(_translate("VistaInicioSubirDatos", "Nueva Ventana"))
        self.actionGuardar.setText(_translate("VistaInicioSubirDatos", "Guardar"))
        self.actionGuardar_Como.setText(_translate("VistaInicioSubirDatos", "Guardar Como "))
        self.actionSalir.setText(_translate("VistaInicioSubirDatos", "Salir "))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaInicioSubirDatos = QtWidgets.QMainWindow()
    ui = Ui_VistaInicioSubirDatos()
    ui.setupUi(VistaInicioSubirDatos)
    VistaInicioSubirDatos.show()
    sys.exit(app.exec_())
