# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VistaFiltros.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets

from UI.Recursos import images_rc

class Ui_VistaFiltros(object):
    def setupUi(self, VistaFiltros):
        VistaFiltros.setObjectName("VistaFiltros")
        VistaFiltros.resize(1378, 817)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VistaFiltros.sizePolicy().hasHeightForWidth())
        VistaFiltros.setSizePolicy(sizePolicy)
        VistaFiltros.setMinimumSize(QtCore.QSize(1280, 720))
        VistaFiltros.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(VistaFiltros)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 500, 571, 341))
        font = QtGui.QFont()
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 541, 381))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.layoutWidget.setFont(font)
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonLimpiarSeleccion3G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLimpiarSeleccion3G.sizePolicy().hasHeightForWidth())
        self.pushButtonLimpiarSeleccion3G.setSizePolicy(sizePolicy)
        self.pushButtonLimpiarSeleccion3G.setMinimumSize(QtCore.QSize(0, 15))
        self.pushButtonLimpiarSeleccion3G.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLimpiarSeleccion3G.setFont(font)
        self.pushButtonLimpiarSeleccion3G.setStyleSheet("background-color: rgb(207, 223, 255);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/Recursos/47559.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonLimpiarSeleccion3G.setIcon(icon)
        self.pushButtonLimpiarSeleccion3G.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonLimpiarSeleccion3G.setObjectName("pushButtonLimpiarSeleccion3G")
        self.gridLayout.addWidget(self.pushButtonLimpiarSeleccion3G, 4, 1, 1, 1)
        self.pushButtonLimpiarSeleccion4G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLimpiarSeleccion4G.sizePolicy().hasHeightForWidth())
        self.pushButtonLimpiarSeleccion4G.setSizePolicy(sizePolicy)
        self.pushButtonLimpiarSeleccion4G.setMinimumSize(QtCore.QSize(0, 15))
        self.pushButtonLimpiarSeleccion4G.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLimpiarSeleccion4G.setFont(font)
        self.pushButtonLimpiarSeleccion4G.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"")
        self.pushButtonLimpiarSeleccion4G.setIcon(icon)
        self.pushButtonLimpiarSeleccion4G.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonLimpiarSeleccion4G.setObjectName("pushButtonLimpiarSeleccion4G")
        self.gridLayout.addWidget(self.pushButtonLimpiarSeleccion4G, 4, 2, 1, 1)
        self.LabeltITULOLASTLAC_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabeltITULOLASTLAC_3.sizePolicy().hasHeightForWidth())
        self.LabeltITULOLASTLAC_3.setSizePolicy(sizePolicy)
        self.LabeltITULOLASTLAC_3.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabeltITULOLASTLAC_3.setFont(font)
        self.LabeltITULOLASTLAC_3.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"")
        self.LabeltITULOLASTLAC_3.setObjectName("LabeltITULOLASTLAC_3")
        self.gridLayout.addWidget(self.LabeltITULOLASTLAC_3, 2, 2, 1, 1)
        self.LabeltITULOLASTLAC = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabeltITULOLASTLAC.sizePolicy().hasHeightForWidth())
        self.LabeltITULOLASTLAC.setSizePolicy(sizePolicy)
        self.LabeltITULOLASTLAC.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabeltITULOLASTLAC.setFont(font)
        self.LabeltITULOLASTLAC.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.LabeltITULOLASTLAC.setObjectName("LabeltITULOLASTLAC")
        self.gridLayout.addWidget(self.LabeltITULOLASTLAC, 2, 0, 1, 1)
        self.pushButtonLimpiarSeleccion2G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLimpiarSeleccion2G.sizePolicy().hasHeightForWidth())
        self.pushButtonLimpiarSeleccion2G.setSizePolicy(sizePolicy)
        self.pushButtonLimpiarSeleccion2G.setMinimumSize(QtCore.QSize(0, 15))
        self.pushButtonLimpiarSeleccion2G.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonLimpiarSeleccion2G.setFont(font)
        self.pushButtonLimpiarSeleccion2G.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.pushButtonLimpiarSeleccion2G.setIcon(icon)
        self.pushButtonLimpiarSeleccion2G.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonLimpiarSeleccion2G.setObjectName("pushButtonLimpiarSeleccion2G")
        self.gridLayout.addWidget(self.pushButtonLimpiarSeleccion2G, 4, 0, 1, 1)
        self.LabeltITULOLASTLAC_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabeltITULOLASTLAC_2.sizePolicy().hasHeightForWidth())
        self.LabeltITULOLASTLAC_2.setSizePolicy(sizePolicy)
        self.LabeltITULOLASTLAC_2.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabeltITULOLASTLAC_2.setFont(font)
        self.LabeltITULOLASTLAC_2.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.LabeltITULOLASTLAC_2.setObjectName("LabeltITULOLASTLAC_2")
        self.gridLayout.addWidget(self.LabeltITULOLASTLAC_2, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 9, 1, 1, 1)
        self.pushButtonLastLac2G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLastLac2G.sizePolicy().hasHeightForWidth())
        self.pushButtonLastLac2G.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        self.pushButtonLastLac2G.setFont(font)
        self.pushButtonLastLac2G.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.pushButtonLastLac2G.setObjectName("pushButtonLastLac2G")
        self.gridLayout.addWidget(self.pushButtonLastLac2G, 3, 0, 1, 1)
        self.pushButtonLastLac3G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLastLac3G.sizePolicy().hasHeightForWidth())
        self.pushButtonLastLac3G.setSizePolicy(sizePolicy)
        self.pushButtonLastLac3G.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.pushButtonLastLac3G.setObjectName("pushButtonLastLac3G")
        self.gridLayout.addWidget(self.pushButtonLastLac3G, 3, 1, 1, 1)
        self.pushButtonLastLac4G = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonLastLac4G.sizePolicy().hasHeightForWidth())
        self.pushButtonLastLac4G.setSizePolicy(sizePolicy)
        self.pushButtonLastLac4G.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"\n"
"")
        self.pushButtonLastLac4G.setObjectName("pushButtonLastLac4G")
        self.gridLayout.addWidget(self.pushButtonLastLac4G, 3, 2, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 260, 571, 241))
        font = QtGui.QFont()
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 551, 221))
        font = QtGui.QFont()
        self.layoutWidget1.setFont(font)
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEditValorRangoFinalMSPOWER2G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoFinalMSPOWER2G.setFont(font)
        self.lineEditValorRangoFinalMSPOWER2G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoFinalMSPOWER2G.setObjectName("lineEditValorRangoFinalMSPOWER2G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoFinalMSPOWER2G, 8, 0, 1, 1)
        self.LabelRangoFinalMSPOWER = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelRangoFinalMSPOWER.sizePolicy().hasHeightForWidth())
        self.LabelRangoFinalMSPOWER.setSizePolicy(sizePolicy)
        self.LabelRangoFinalMSPOWER.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelRangoFinalMSPOWER.setFont(font)
        self.LabelRangoFinalMSPOWER.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LabelRangoFinalMSPOWER.setObjectName("LabelRangoFinalMSPOWER")
        self.gridLayout_3.addWidget(self.LabelRangoFinalMSPOWER, 7, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.checkBoxTomarDatoMSPower3G = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxTomarDatoMSPower3G.setFont(font)
        self.checkBoxTomarDatoMSPower3G.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.checkBoxTomarDatoMSPower3G.setObjectName("checkBoxTomarDatoMSPower3G")
        self.gridLayout_3.addWidget(self.checkBoxTomarDatoMSPower3G, 0, 1, 1, 1)
        self.LabelMSPOWER = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelMSPOWER.sizePolicy().hasHeightForWidth())
        self.LabelMSPOWER.setSizePolicy(sizePolicy)
        self.LabelMSPOWER.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelMSPOWER.setFont(font)
        self.LabelMSPOWER.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.LabelMSPOWER.setObjectName("LabelMSPOWER")
        self.gridLayout_3.addWidget(self.LabelMSPOWER, 1, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.LabelMSPOWER_3 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelMSPOWER_3.sizePolicy().hasHeightForWidth())
        self.LabelMSPOWER_3.setSizePolicy(sizePolicy)
        self.LabelMSPOWER_3.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelMSPOWER_3.setFont(font)
        self.LabelMSPOWER_3.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"")
        self.LabelMSPOWER_3.setObjectName("LabelMSPOWER_3")
        self.gridLayout_3.addWidget(self.LabelMSPOWER_3, 1, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.LabelRangoInciaMSPOWER = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelRangoInciaMSPOWER.sizePolicy().hasHeightForWidth())
        self.LabelRangoInciaMSPOWER.setSizePolicy(sizePolicy)
        self.LabelRangoInciaMSPOWER.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelRangoInciaMSPOWER.setFont(font)
        self.LabelRangoInciaMSPOWER.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LabelRangoInciaMSPOWER.setObjectName("LabelRangoInciaMSPOWER")
        self.gridLayout_3.addWidget(self.LabelRangoInciaMSPOWER, 3, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.LabelMSPOWER_2 = QtWidgets.QLabel(self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelMSPOWER_2.sizePolicy().hasHeightForWidth())
        self.LabelMSPOWER_2.setSizePolicy(sizePolicy)
        self.LabelMSPOWER_2.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelMSPOWER_2.setFont(font)
        self.LabelMSPOWER_2.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.LabelMSPOWER_2.setObjectName("LabelMSPOWER_2")
        self.gridLayout_3.addWidget(self.LabelMSPOWER_2, 1, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.lineEditValorRangoFinalMSPOWER3G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoFinalMSPOWER3G.setFont(font)
        self.lineEditValorRangoFinalMSPOWER3G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoFinalMSPOWER3G.setObjectName("lineEditValorRangoFinalMSPOWER3G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoFinalMSPOWER3G, 8, 1, 1, 1)
        self.checkBoxTomarDatoMSPower2G = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxTomarDatoMSPower2G.setFont(font)
        self.checkBoxTomarDatoMSPower2G.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.checkBoxTomarDatoMSPower2G.setObjectName("checkBoxTomarDatoMSPower2G")
        self.gridLayout_3.addWidget(self.checkBoxTomarDatoMSPower2G, 0, 0, 1, 1)
        self.checkBoxTomarDatoMSPower4G = QtWidgets.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.checkBoxTomarDatoMSPower4G.setFont(font)
        self.checkBoxTomarDatoMSPower4G.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"")
        self.checkBoxTomarDatoMSPower4G.setObjectName("checkBoxTomarDatoMSPower4G")
        self.gridLayout_3.addWidget(self.checkBoxTomarDatoMSPower4G, 0, 2, 1, 1)
        self.lineEditValorRangoFinalMSPOWER4G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoFinalMSPOWER4G.setFont(font)
        self.lineEditValorRangoFinalMSPOWER4G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoFinalMSPOWER4G.setObjectName("lineEditValorRangoFinalMSPOWER4G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoFinalMSPOWER4G, 8, 2, 1, 1)
        self.lineEditValorRangoInicialMSPOWER3G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoInicialMSPOWER3G.setFont(font)
        self.lineEditValorRangoInicialMSPOWER3G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoInicialMSPOWER3G.setObjectName("lineEditValorRangoInicialMSPOWER3G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoInicialMSPOWER3G, 4, 1, 1, 1)
        self.lineEditValorRangoInicialMSPOWER2G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoInicialMSPOWER2G.setFont(font)
        self.lineEditValorRangoInicialMSPOWER2G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoInicialMSPOWER2G.setObjectName("lineEditValorRangoInicialMSPOWER2G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoInicialMSPOWER2G, 4, 0, 1, 1)
        self.lineEditValorRangoInicialMSPOWER4G = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        self.lineEditValorRangoInicialMSPOWER4G.setFont(font)
        self.lineEditValorRangoInicialMSPOWER4G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangoInicialMSPOWER4G.setObjectName("lineEditValorRangoInicialMSPOWER4G")
        self.gridLayout_3.addWidget(self.lineEditValorRangoInicialMSPOWER4G, 4, 2, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 70, 561, 171))
        font = QtGui.QFont()
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget2.setGeometry(QtCore.QRect(6, 12, 551, 179))
        font = QtGui.QFont()
        self.layoutWidget2.setFont(font)
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.LabelTiempoAvance_2 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelTiempoAvance_2.setFont(font)
        self.LabelTiempoAvance_2.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.LabelTiempoAvance_2.setObjectName("LabelTiempoAvance_2")
        self.gridLayout_2.addWidget(self.LabelTiempoAvance_2, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(0, 15))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 4, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 5, 2, 1, 1)
        self.lineEditValorHitsMinimos3G = QtWidgets.QLineEdit(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditValorHitsMinimos3G.sizePolicy().hasHeightForWidth())
        self.lineEditValorHitsMinimos3G.setSizePolicy(sizePolicy)
        self.lineEditValorHitsMinimos3G.setMaximumSize(QtCore.QSize(167, 167))
        font = QtGui.QFont()
        self.lineEditValorHitsMinimos3G.setFont(font)
        self.lineEditValorHitsMinimos3G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorHitsMinimos3G.setObjectName("lineEditValorHitsMinimos3G")
        self.gridLayout_2.addWidget(self.lineEditValorHitsMinimos3G, 4, 3, 1, 1)
        self.lineEditValorRangosTA4G = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        self.lineEditValorRangosTA4G.setFont(font)
        self.lineEditValorRangosTA4G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangosTA4G.setObjectName("lineEditValorRangosTA4G")
        self.gridLayout_2.addWidget(self.lineEditValorRangosTA4G, 2, 4, 1, 1)
        self.lineEditValorRangosTA3G = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        self.lineEditValorRangosTA3G.setFont(font)
        self.lineEditValorRangosTA3G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangosTA3G.setObjectName("lineEditValorRangosTA3G")
        self.gridLayout_2.addWidget(self.lineEditValorRangosTA3G, 2, 3, 1, 1)
        self.LabelTiempoAvance = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelTiempoAvance.sizePolicy().hasHeightForWidth())
        self.LabelTiempoAvance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelTiempoAvance.setFont(font)
        self.LabelTiempoAvance.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.LabelTiempoAvance.setObjectName("LabelTiempoAvance")
        self.gridLayout_2.addWidget(self.LabelTiempoAvance, 0, 2, 1, 1)
        self.LabelRangoFinallTA = QtWidgets.QLabel(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.LabelRangoFinallTA.sizePolicy().hasHeightForWidth())
        self.LabelRangoFinallTA.setSizePolicy(sizePolicy)
        self.LabelRangoFinallTA.setMaximumSize(QtCore.QSize(677, 167))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelRangoFinallTA.setFont(font)
        self.LabelRangoFinallTA.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LabelRangoFinallTA.setObjectName("LabelRangoFinallTA")
        self.gridLayout_2.addWidget(self.LabelRangoFinallTA, 3, 1, 1, 5, QtCore.Qt.AlignHCenter)
        self.lineEditValorRangosTA2G = QtWidgets.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        self.lineEditValorRangosTA2G.setFont(font)
        self.lineEditValorRangosTA2G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorRangosTA2G.setObjectName("lineEditValorRangosTA2G")
        self.gridLayout_2.addWidget(self.lineEditValorRangosTA2G, 2, 2, 1, 1)
        self.lineEditValorHitsMinimos2G = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditValorHitsMinimos2G.setMaximumSize(QtCore.QSize(167, 167))
        font = QtGui.QFont()
        self.lineEditValorHitsMinimos2G.setFont(font)
        self.lineEditValorHitsMinimos2G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorHitsMinimos2G.setObjectName("lineEditValorHitsMinimos2G")
        self.gridLayout_2.addWidget(self.lineEditValorHitsMinimos2G, 4, 2, 1, 1)
        self.lineEditValorHitsMinimos4G = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEditValorHitsMinimos4G.setMaximumSize(QtCore.QSize(167, 167))
        font = QtGui.QFont()
        self.lineEditValorHitsMinimos4G.setFont(font)
        self.lineEditValorHitsMinimos4G.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEditValorHitsMinimos4G.setObjectName("lineEditValorHitsMinimos4G")
        self.gridLayout_2.addWidget(self.lineEditValorHitsMinimos4G, 4, 4, 1, 1)
        self.LabelTiempoAvance_3 = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.LabelTiempoAvance_3.setFont(font)
        self.LabelTiempoAvance_3.setStyleSheet("background-color: rgb(255, 146, 146);\n"
"")
        self.LabelTiempoAvance_3.setObjectName("LabelTiempoAvance_3")
        self.gridLayout_2.addWidget(self.LabelTiempoAvance_3, 0, 4, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 491, 51))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEditBuscarDatos = QtWidgets.QTextEdit(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditBuscarDatos.sizePolicy().hasHeightForWidth())
        self.textEditBuscarDatos.setSizePolicy(sizePolicy)
        self.textEditBuscarDatos.setMinimumSize(QtCore.QSize(3, 3))
        self.textEditBuscarDatos.setMaximumSize(QtCore.QSize(1000, 50))
        self.textEditBuscarDatos.setSizeIncrement(QtCore.QSize(9, 9))
        self.textEditBuscarDatos.setBaseSize(QtCore.QSize(9, 9))
        self.textEditBuscarDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBuscarDatos.setObjectName("textEditBuscarDatos")
        self.horizontalLayout.addWidget(self.textEditBuscarDatos)
        self.pushButtonBuscarDatos = QtWidgets.QPushButton(self.layoutWidget3)
        self.pushButtonBuscarDatos.setMaximumSize(QtCore.QSize(167, 16777215))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonBuscarDatos.setFont(font)
        self.pushButtonBuscarDatos.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/icons8-google-web-search-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBuscarDatos.setIcon(icon1)
        self.pushButtonBuscarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonBuscarDatos.setObjectName("pushButtonBuscarDatos")
        self.horizontalLayout.addWidget(self.pushButtonBuscarDatos)
        self.pushButtonObtenerDatosFiltrados = QtWidgets.QPushButton(self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonObtenerDatosFiltrados.sizePolicy().hasHeightForWidth())
        self.pushButtonObtenerDatosFiltrados.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonObtenerDatosFiltrados.setFont(font)
        self.pushButtonObtenerDatosFiltrados.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/icons8-hand-box-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonObtenerDatosFiltrados.setIcon(icon2)
        self.pushButtonObtenerDatosFiltrados.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonObtenerDatosFiltrados.setObjectName("pushButtonObtenerDatosFiltrados")
        self.horizontalLayout.addWidget(self.pushButtonObtenerDatosFiltrados)
        self.gridLayout_4.addWidget(self.groupBox, 7, 2, 10, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButtonVerAnalisis = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonVerAnalisis.setFont(font)
        self.pushButtonVerAnalisis.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.pushButtonVerAnalisis.setIcon(icon2)
        self.pushButtonVerAnalisis.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerAnalisis.setObjectName("pushButtonVerAnalisis")
        self.gridLayout_5.addWidget(self.pushButtonVerAnalisis, 0, 2, 1, 1)
        self.pushButtonGuardarBusqueda = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGuardarBusqueda.sizePolicy().hasHeightForWidth())
        self.pushButtonGuardarBusqueda.setSizePolicy(sizePolicy)
        self.pushButtonGuardarBusqueda.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonGuardarBusqueda.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonGuardarBusqueda.setFont(font)
        self.pushButtonGuardarBusqueda.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Iconos/icons8-añadir-libro-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGuardarBusqueda.setIcon(icon3)
        self.pushButtonGuardarBusqueda.setIconSize(QtCore.QSize(30, 40))
        self.pushButtonGuardarBusqueda.setObjectName("pushButtonGuardarBusqueda")
        self.gridLayout_5.addWidget(self.pushButtonGuardarBusqueda, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pushButtonGenerarGraficas = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonGenerarGraficas.sizePolicy().hasHeightForWidth())
        self.pushButtonGenerarGraficas.setSizePolicy(sizePolicy)
        self.pushButtonGenerarGraficas.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonGenerarGraficas.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.pushButtonGenerarGraficas.setFont(font)
        self.pushButtonGenerarGraficas.setStyleSheet("background-color: rgb(255, 255, 127);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Iconos/graficas.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGenerarGraficas.setIcon(icon4)
        self.pushButtonGenerarGraficas.setIconSize(QtCore.QSize(30, 40))
        self.pushButtonGenerarGraficas.setObjectName("pushButtonGenerarGraficas")
        self.gridLayout_5.addWidget(self.pushButtonGenerarGraficas, 0, 4, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_4.addLayout(self.gridLayout_5, 14, 1, 1, 1)
        self.tableWidgetMostrarSeleccion = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetMostrarSeleccion.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetMostrarSeleccion.setObjectName("tableWidgetMostrarSeleccion")
        self.tableWidgetMostrarSeleccion.setColumnCount(0)
        self.tableWidgetMostrarSeleccion.setRowCount(0)
        self.gridLayout_4.addWidget(self.tableWidgetMostrarSeleccion, 15, 1, 1, 1)
        self.tableWidgetVerDatosFiltrados = QtWidgets.QTableWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidgetVerDatosFiltrados.sizePolicy().hasHeightForWidth())
        self.tableWidgetVerDatosFiltrados.setSizePolicy(sizePolicy)
        self.tableWidgetVerDatosFiltrados.setMinimumSize(QtCore.QSize(700, 0))
        self.tableWidgetVerDatosFiltrados.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetVerDatosFiltrados.setObjectName("tableWidgetVerDatosFiltrados")
        self.tableWidgetVerDatosFiltrados.setColumnCount(6)
        self.tableWidgetVerDatosFiltrados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetVerDatosFiltrados.setHorizontalHeaderItem(5, item)
        self.gridLayout_4.addWidget(self.tableWidgetVerDatosFiltrados, 12, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_4.addItem(spacerItem2, 16, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/logoRaptor.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.gridLayout_7.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_7.setSpacing(3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4.addLayout(self.gridLayout_7, 12, 3, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(23)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.labelRAT = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRAT.setFont(font)
        self.labelRAT.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelRAT.setObjectName("labelRAT")
        self.gridLayout_6.addWidget(self.labelRAT, 0, 0, 1, 1)
        self.checkBox3G = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox3G.setStyleSheet("background-color: rgb(207, 223, 255);")
        self.checkBox3G.setObjectName("checkBox3G")
        self.gridLayout_6.addWidget(self.checkBox3G, 4, 0, 1, 1)
        self.checkBox2G = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox2G.setStyleSheet("background-color: rgb(155, 255, 144);")
        self.checkBox2G.setObjectName("checkBox2G")
        self.gridLayout_6.addWidget(self.checkBox2G, 3, 0, 1, 1)
        self.checkBox4G = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox4G.setStyleSheet("background-color: rgb(255, 146, 146);")
        self.checkBox4G.setObjectName("checkBox4G")
        self.gridLayout_6.addWidget(self.checkBox4G, 5, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_6, 12, 0, 1, 1)
        VistaFiltros.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VistaFiltros)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1378, 26))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        VistaFiltros.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VistaFiltros)
        self.statusbar.setObjectName("statusbar")
        VistaFiltros.setStatusBar(self.statusbar)
        self.actionIrADatosGenerales = QtWidgets.QAction(VistaFiltros)
        self.actionIrADatosGenerales.setObjectName("actionIrADatosGenerales")
        self.actionNueva_Ventana = QtWidgets.QAction(VistaFiltros)
        self.actionNueva_Ventana.setObjectName("actionNueva_Ventana")
        self.actionGuardar = QtWidgets.QAction(VistaFiltros)
        self.actionGuardar.setObjectName("actionGuardar")
        self.actionGuargar_Como = QtWidgets.QAction(VistaFiltros)
        self.actionGuargar_Como.setObjectName("actionGuargar_Como")
        self.menuArchivo.addAction(self.actionIrADatosGenerales)
        self.menubar.addAction(self.menuArchivo.menuAction())

        self.retranslateUi(VistaFiltros)
        QtCore.QMetaObject.connectSlotsByName(VistaFiltros)
        VistaFiltros.setTabOrder(self.checkBox2G, self.checkBox3G)
        VistaFiltros.setTabOrder(self.checkBox3G, self.checkBox4G)
        VistaFiltros.setTabOrder(self.checkBox4G, self.textEditBuscarDatos)
        VistaFiltros.setTabOrder(self.textEditBuscarDatos, self.pushButtonBuscarDatos)
        VistaFiltros.setTabOrder(self.pushButtonBuscarDatos, self.pushButtonObtenerDatosFiltrados)
        VistaFiltros.setTabOrder(self.pushButtonObtenerDatosFiltrados, self.lineEditValorRangosTA2G)
        VistaFiltros.setTabOrder(self.lineEditValorRangosTA2G, self.lineEditValorRangosTA3G)
        VistaFiltros.setTabOrder(self.lineEditValorRangosTA3G, self.lineEditValorRangosTA4G)
        VistaFiltros.setTabOrder(self.lineEditValorRangosTA4G, self.lineEditValorHitsMinimos2G)
        VistaFiltros.setTabOrder(self.lineEditValorHitsMinimos2G, self.lineEditValorHitsMinimos3G)
        VistaFiltros.setTabOrder(self.lineEditValorHitsMinimos3G, self.lineEditValorHitsMinimos4G)
        VistaFiltros.setTabOrder(self.lineEditValorHitsMinimos4G, self.checkBoxTomarDatoMSPower2G)
        VistaFiltros.setTabOrder(self.checkBoxTomarDatoMSPower2G, self.checkBoxTomarDatoMSPower3G)
        VistaFiltros.setTabOrder(self.checkBoxTomarDatoMSPower3G, self.checkBoxTomarDatoMSPower4G)
        VistaFiltros.setTabOrder(self.checkBoxTomarDatoMSPower4G, self.lineEditValorRangoInicialMSPOWER2G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoInicialMSPOWER2G, self.lineEditValorRangoInicialMSPOWER3G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoInicialMSPOWER3G, self.lineEditValorRangoInicialMSPOWER4G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoInicialMSPOWER4G, self.lineEditValorRangoFinalMSPOWER2G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoFinalMSPOWER2G, self.lineEditValorRangoFinalMSPOWER3G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoFinalMSPOWER3G, self.lineEditValorRangoFinalMSPOWER4G)
        VistaFiltros.setTabOrder(self.lineEditValorRangoFinalMSPOWER4G, self.pushButtonLastLac2G)
        VistaFiltros.setTabOrder(self.pushButtonLastLac2G, self.pushButtonLastLac3G)
        VistaFiltros.setTabOrder(self.pushButtonLastLac3G, self.pushButtonLastLac4G)
        VistaFiltros.setTabOrder(self.pushButtonLastLac4G, self.pushButtonGenerarGraficas)
        VistaFiltros.setTabOrder(self.pushButtonGenerarGraficas, self.tableWidgetMostrarSeleccion)
        VistaFiltros.setTabOrder(self.tableWidgetMostrarSeleccion, self.tableWidgetVerDatosFiltrados)
        VistaFiltros.setTabOrder(self.tableWidgetVerDatosFiltrados, self.pushButtonLimpiarSeleccion4G)
        VistaFiltros.setTabOrder(self.pushButtonLimpiarSeleccion4G, self.pushButtonLimpiarSeleccion3G)
        VistaFiltros.setTabOrder(self.pushButtonLimpiarSeleccion3G, self.pushButtonLimpiarSeleccion2G)
        VistaFiltros.setTabOrder(self.pushButtonLimpiarSeleccion2G, self.pushButtonGuardarBusqueda)
        VistaFiltros.setTabOrder(self.pushButtonGuardarBusqueda, self.pushButtonVerAnalisis)

    def retranslateUi(self, VistaFiltros):
        _translate = QtCore.QCoreApplication.translate
        VistaFiltros.setWindowTitle(_translate("VistaFiltros", "MainWindow"))
        self.groupBox.setTitle(_translate("VistaFiltros", "LISTA FILTROS"))
        self.groupBox_2.setTitle(_translate("VistaFiltros", "LAST LAC"))
        self.pushButtonLimpiarSeleccion3G.setText(_translate("VistaFiltros", "Limpiar Selección"))
        self.pushButtonLimpiarSeleccion4G.setText(_translate("VistaFiltros", "Limpiar Selección"))
        self.LabeltITULOLASTLAC_3.setText(_translate("VistaFiltros", "            LAST LAC (4G)"))
        self.LabeltITULOLASTLAC.setText(_translate("VistaFiltros", "         LAST LAC (2G)"))
        self.pushButtonLimpiarSeleccion2G.setText(_translate("VistaFiltros", "Limpiar Selección"))
        self.LabeltITULOLASTLAC_2.setText(_translate("VistaFiltros", "          LAST LAC (3G)"))
        self.pushButtonLastLac2G.setText(_translate("VistaFiltros", "DATOS LAST LAC"))
        self.pushButtonLastLac3G.setText(_translate("VistaFiltros", "DATOS LAST LAC"))
        self.pushButtonLastLac4G.setText(_translate("VistaFiltros", "DATOS LAST LAC"))
        self.groupBox_3.setTitle(_translate("VistaFiltros", "MS POWER"))
        self.LabelRangoFinalMSPOWER.setText(_translate("VistaFiltros", "DATOS FINALES"))
        self.checkBoxTomarDatoMSPower3G.setText(_translate("VistaFiltros", "Tomar Dato"))
        self.LabelMSPOWER.setText(_translate("VistaFiltros", " MS POWER (2G)"))
        self.LabelMSPOWER_3.setText(_translate("VistaFiltros", " MS POWER (4G)"))
        self.LabelRangoInciaMSPOWER.setText(_translate("VistaFiltros", " DATOS  INICIALES"))
        self.LabelMSPOWER_2.setText(_translate("VistaFiltros", " MS POWER (3G)"))
        self.checkBoxTomarDatoMSPower2G.setText(_translate("VistaFiltros", "Tomar Dato"))
        self.checkBoxTomarDatoMSPower4G.setText(_translate("VistaFiltros", "Tomar Dato"))
        self.groupBox_4.setTitle(_translate("VistaFiltros", "TA"))
        self.LabelTiempoAvance_2.setText(_translate("VistaFiltros", "          TA (3G)"))
        self.label_2.setText(_translate("VistaFiltros", "VALORES TA"))
        self.lineEditValorHitsMinimos3G.setPlaceholderText(_translate("VistaFiltros", "0"))
        self.LabelTiempoAvance.setText(_translate("VistaFiltros", "         TA (2G)"))
        self.LabelRangoFinallTA.setText(_translate("VistaFiltros", "CANTIDAD HITS MINIMOS"))
        self.lineEditValorHitsMinimos2G.setPlaceholderText(_translate("VistaFiltros", "0"))
        self.lineEditValorHitsMinimos4G.setPlaceholderText(_translate("VistaFiltros", "0"))
        self.LabelTiempoAvance_3.setText(_translate("VistaFiltros", "           TA (4G)"))
        self.pushButtonBuscarDatos.setText(_translate("VistaFiltros", "Buscar En Tabla"))
        self.pushButtonObtenerDatosFiltrados.setText(_translate("VistaFiltros", "Obtener Datos "))
        self.pushButtonVerAnalisis.setText(_translate("VistaFiltros", " Ver Reportes "))
        self.pushButtonGuardarBusqueda.setText(_translate("VistaFiltros", "Guardar Tabla Actual"))
        self.pushButtonGenerarGraficas.setText(_translate("VistaFiltros", "Generar Gráficas "))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(0)
        item.setText(_translate("VistaFiltros", "IMEI"))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(1)
        item.setText(_translate("VistaFiltros", "IMSIS Asociados"))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(2)
        item.setText(_translate("VistaFiltros", "Operator"))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(3)
        item.setText(_translate("VistaFiltros", "Channel"))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(4)
        item.setText(_translate("VistaFiltros", "Hits"))
        item = self.tableWidgetVerDatosFiltrados.horizontalHeaderItem(5)
        item.setText(_translate("VistaFiltros", "Data-Time"))
        self.label.setText(_translate("VistaFiltros", "FILTRAR DATOS"))
        self.labelRAT.setText(_translate("VistaFiltros", "RAT"))
        self.checkBox3G.setText(_translate("VistaFiltros", "3G"))
        self.checkBox2G.setText(_translate("VistaFiltros", "2G"))
        self.checkBox4G.setText(_translate("VistaFiltros", "4G"))
        self.menuArchivo.setTitle(_translate("VistaFiltros", "Archivo "))
        self.actionIrADatosGenerales.setText(_translate("VistaFiltros", "Volver Datos Generales"))
        self.actionNueva_Ventana.setText(_translate("VistaFiltros", "Nueva Ventana"))
        self.actionGuardar.setText(_translate("VistaFiltros", "Guardar"))
        self.actionGuargar_Como.setText(_translate("VistaFiltros", "Guargar Como"))
# import DATOS IMAGENES_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaFiltros = QtWidgets.QMainWindow()
    ui = Ui_VistaFiltros()
    ui.setupUi(VistaFiltros)
    VistaFiltros.show()
    sys.exit(app.exec_())
