# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VistaGeneralDatos.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaGeneralDatos(object):
    def setupUi(self, VistaGeneralDatos):
        VistaGeneralDatos.setObjectName("vistaGeneralDatos")
        VistaGeneralDatos.resize(1280, 840)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VistaGeneralDatos.sizePolicy().hasHeightForWidth())
        VistaGeneralDatos.setSizePolicy(sizePolicy)
        VistaGeneralDatos.setMinimumSize(QtCore.QSize(1280, 720))
        VistaGeneralDatos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(85, 125, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(VistaGeneralDatos)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout_2 = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout_2.setObjectName("formLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonGuardarImsisVSImei = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonGuardarImsisVSImei.setFont(font)
        self.pushButtonGuardarImsisVSImei.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons8-añadir-libro-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGuardarImsisVSImei.setIcon(icon)
        self.pushButtonGuardarImsisVSImei.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGuardarImsisVSImei.setObjectName("pushButtonGuardarImsisVSImei")
        self.gridLayout.addWidget(self.pushButtonGuardarImsisVSImei, 21, 1, 1, 1)
        self.pushButtonVerImsisVSImeis = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonVerImsisVSImeis.setFont(font)
        self.pushButtonVerImsisVSImeis.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-big-data-150.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVerImsisVSImeis.setIcon(icon1)
        self.pushButtonVerImsisVSImeis.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerImsisVSImeis.setObjectName("pushButtonVerImsisVSImeis")
        self.gridLayout.addWidget(self.pushButtonVerImsisVSImeis, 20, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addWidget(self.frame, 28, 4, 1, 1)
        self.pushButtonAnalisisHorario = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonAnalisisHorario.setFont(font)
        self.pushButtonAnalisisHorario.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Recursos/icons8-tiempo-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAnalisisHorario.setIcon(icon2)
        self.pushButtonAnalisisHorario.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonAnalisisHorario.setObjectName("pushButtonAnalisisHorario")
        self.gridLayout.addWidget(self.pushButtonAnalisisHorario, 25, 1, 1, 1)
        self.pushButtonFiltrarDatos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonFiltrarDatos.setFont(font)
        self.pushButtonFiltrarDatos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Recursos/icons8-ver-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFiltrarDatos.setIcon(icon3)
        self.pushButtonFiltrarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonFiltrarDatos.setObjectName("pushButtonFiltrarDatos")
        self.gridLayout.addWidget(self.pushButtonFiltrarDatos, 24, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("background-image: url(:/Imagenes/Logo.png);\n"
"image: url(:/newPrefix/Logo.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 48, 20, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButtonRATS = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRATS.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonRATS.setObjectName("pushButtonRATS")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.pushButtonRATS)
        self.labelRATContador = QtWidgets.QLabel(self.centralwidget)
        self.labelRATContador.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelRATContador.setText("")
        self.labelRATContador.setObjectName("labelRATContador")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelRATContador)
        self.pushButtonOperadores = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOperadores.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonOperadores.setObjectName("pushButtonOperadores")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButtonOperadores)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.labelOperadorDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelOperadorDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelOperadorDatos.setText("")
        self.labelOperadorDatos.setObjectName("labelOperadorDatos")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelOperadorDatos)
        self.labelIMSIDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelIMSIDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelIMSIDatos.setText("")
        self.labelIMSIDatos.setObjectName("labelIMSIDatos")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelIMSIDatos)
        self.labelIMEIDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelIMEIDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelIMEIDatos.setText("")
        self.labelIMEIDatos.setObjectName("labelIMEIDatos")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelIMEIDatos)
        self.textEditBuscarDatos = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditBuscarDatos.sizePolicy().hasHeightForWidth())
        self.textEditBuscarDatos.setSizePolicy(sizePolicy)
        self.textEditBuscarDatos.setMaximumSize(QtCore.QSize(600, 50))
        self.textEditBuscarDatos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEditBuscarDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBuscarDatos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEditBuscarDatos.setObjectName("textEditBuscarDatos")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.textEditBuscarDatos)
        self.pushButtonBuscarDato = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonBuscarDato.setFont(font)
        self.pushButtonBuscarDato.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonBuscarDato.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons8-google-web-search-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBuscarDato.setIcon(icon4)
        self.pushButtonBuscarDato.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonBuscarDato.setObjectName("pushButtonBuscarDato")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButtonBuscarDato)
        self.gridLayout.addLayout(self.formLayout, 14, 1, 3, 1)
        self.pushButtonVerDatosIncidentales = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonVerDatosIncidentales.setFont(font)
        self.pushButtonVerDatosIncidentales.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Recursos/icons8-big-data-150.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVerDatosIncidentales.setIcon(icon5)
        self.pushButtonVerDatosIncidentales.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerDatosIncidentales.setObjectName("pushButtonVerDatosIncidentales")
        self.gridLayout.addWidget(self.pushButtonVerDatosIncidentales, 18, 1, 1, 1)
        self.pushButtonGuardarDatos4G = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonGuardarDatos4G.setFont(font)
        self.pushButtonGuardarDatos4G.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonGuardarDatos4G.setIcon(icon)
        self.pushButtonGuardarDatos4G.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGuardarDatos4G.setObjectName("pushButtonGuardarDatos4G")
        self.gridLayout.addWidget(self.pushButtonGuardarDatos4G, 22, 1, 1, 1)
        self.pushButtonVerTablaOriginal = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonVerTablaOriginal.setFont(font)
        self.pushButtonVerTablaOriginal.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonVerTablaOriginal.setIcon(icon5)
        self.pushButtonVerTablaOriginal.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerTablaOriginal.setObjectName("pushButtonVerTablaOriginal")
        self.gridLayout.addWidget(self.pushButtonVerTablaOriginal, 19, 1, 1, 1)
        self.pushButtonGuardarDatos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonGuardarDatos.setFont(font)
        self.pushButtonGuardarDatos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Recursos/upload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGuardarDatos.setIcon(icon6)
        self.pushButtonGuardarDatos.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonGuardarDatos.setObjectName("pushButtonGuardarDatos")
        self.gridLayout.addWidget(self.pushButtonGuardarDatos, 26, 1, 1, 1)
        self.tableWidgetDatosExcel = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetDatosExcel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetDatosExcel.setObjectName("tableWidgetDatosExcel")
        self.tableWidgetDatosExcel.setColumnCount(12)
        self.tableWidgetDatosExcel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(11, item)
        self.gridLayout.addWidget(self.tableWidgetDatosExcel, 14, 3, 15, 1)
        self.pushButtonAsignarIMEIS = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonAsignarIMEIS.setFont(font)
        self.pushButtonAsignarIMEIS.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Recursos/icons8-ayuda-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAsignarIMEIS.setIcon(icon7)
        self.pushButtonAsignarIMEIS.setIconSize(QtCore.QSize(60, 60))
        self.pushButtonAsignarIMEIS.setObjectName("pushButtonAsignarIMEIS")
        self.gridLayout.addWidget(self.pushButtonAsignarIMEIS, 17, 1, 1, 1)
        self.formLayout_2.setLayout(2, QtWidgets.QFormLayout.SpanningRole, self.gridLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label)
        VistaGeneralDatos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VistaGeneralDatos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuDatos = QtWidgets.QMenu(self.menubar)
        self.menuDatos.setObjectName("menuDatos")
        VistaGeneralDatos.setMenuBar(self.menubar)
        self.actionIr_A_Principal = QtWidgets.QAction(VistaGeneralDatos)
        self.actionIr_A_Principal.setObjectName("actionIr_A_Principal")
        self.actionGuardar = QtWidgets.QAction(VistaGeneralDatos)
        self.actionGuardar.setObjectName("actionGuardar")
        self.menuDatos.addSeparator()
        self.menuDatos.addAction(self.actionIr_A_Principal)
        self.menuDatos.addAction(self.actionGuardar)
        self.menubar.addAction(self.menuDatos.menuAction())

        self.retranslateUi(VistaGeneralDatos)
        QtCore.QMetaObject.connectSlotsByName(VistaGeneralDatos)

    def retranslateUi(self, VistaGeneralDatos):
        _translate = QtCore.QCoreApplication.translate
        VistaGeneralDatos.setWindowTitle(_translate("VistaGeneralDatos", "MainWindow"))
        self.pushButtonGuardarImsisVSImei.setText(_translate("VistaGeneralDatos", "Guardar IMSIS VS IMEI"))
        self.pushButtonVerImsisVSImeis.setText(_translate("VistaGeneralDatos", "Ver IMSIS VS IMEIS"))
        self.pushButtonAnalisisHorario.setText(_translate("VistaGeneralDatos", "Análisis Horario"))
        self.pushButtonFiltrarDatos.setText(_translate("VistaGeneralDatos", "Filtrar Datos"))
        self.pushButtonRATS.setText(_translate("VistaGeneralDatos", "RAT"))
        self.pushButtonOperadores.setText(_translate("VistaGeneralDatos", "Operador"))
        self.pushButton.setText(_translate("VistaGeneralDatos", "IMSI"))
        self.pushButton_2.setText(_translate("VistaGeneralDatos", "IMEI"))
        self.pushButtonBuscarDato.setText(_translate("VistaGeneralDatos", "Buscar"))
        self.pushButtonVerDatosIncidentales.setText(_translate("VistaGeneralDatos", "Ver Datos Incidentales"))
        self.pushButtonGuardarDatos4G.setText(_translate("VistaGeneralDatos", "Guardar Datos 4G"))
        self.pushButtonVerTablaOriginal.setText(_translate("VistaGeneralDatos", "Ver Tabla original"))
        self.pushButtonGuardarDatos.setText(_translate("VistaGeneralDatos", "Guardar Tabla"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(0)
        item.setText(_translate("VistaGeneralDatos", "RAT"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(1)
        item.setText(_translate("VistaGeneralDatos", "OPERATOR"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(2)
        item.setText(_translate("VistaGeneralDatos", "CHANNEL"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(3)
        item.setText(_translate("VistaGeneralDatos", "IMEI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(4)
        item.setText(_translate("VistaGeneralDatos", "IMSI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(5)
        item.setText(_translate("VistaGeneralDatos", "TMSI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(6)
        item.setText(_translate("VistaGeneralDatos", "MS POWER"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(7)
        item.setText(_translate("VistaGeneralDatos", "TA"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(8)
        item.setText(_translate("VistaGeneralDatos", "LAST LAC"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(9)
        item.setText(_translate("VistaGeneralDatos", "NAME"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(10)
        item.setText(_translate("VistaGeneralDatos", "HITS"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(11)
        item.setText(_translate("VistaGeneralDatos", "DATA-TIME"))
        self.pushButtonAsignarIMEIS.setText(_translate("VistaGeneralDatos", "Asignar IMEI\'S"))
        self.label.setText(_translate("VistaGeneralDatos", "                                                                                                                                                       DATOS GENERALES"))
        self.menuDatos.setTitle(_translate("VistaGeneralDatos", "Datos"))
        self.actionIr_A_Principal.setText(_translate("VistaGeneralDatos", "Ir A Principal "))
        self.actionGuardar.setText(_translate("VistaGeneralDatos", "Guardar "))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaGeneralDatos = QtWidgets.QMainWindow()
    ui = Ui_VistaGeneralDatos()
    ui.setupUi(VistaGeneralDatos)
    VistaGeneralDatos.show()
    sys.exit(app.exec_())
