# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VistaGeneralDatos.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from UI.Recursos import images_rc


class Ui_vistaGeneralDatos(object):
    def setupUi(self, vistaGeneralDatos):
        vistaGeneralDatos.setObjectName("vistaGeneralDatos")
        vistaGeneralDatos.resize(1280, 840)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(vistaGeneralDatos.sizePolicy().hasHeightForWidth())
        vistaGeneralDatos.setSizePolicy(sizePolicy)
        vistaGeneralDatos.setMinimumSize(QtCore.QSize(1280, 720))
        vistaGeneralDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(vistaGeneralDatos)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setStyleSheet("background-image: url(:/Imagenes/Logo.png);\n"
"image: url(:/newPrefix/Logo.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 57, 20, 1, 1)
        self.pushButtonAsignarIMEIS = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonAsignarIMEIS.setFont(font)
        self.pushButtonAsignarIMEIS.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/icons8-ayuda-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAsignarIMEIS.setIcon(icon)
        self.pushButtonAsignarIMEIS.setIconSize(QtCore.QSize(50, 50))
        self.pushButtonAsignarIMEIS.setObjectName("pushButtonAsignarIMEIS")
        self.gridLayout.addWidget(self.pushButtonAsignarIMEIS, 18, 1, 1, 1)
        self.pushButtonVerTablaOriginal = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonVerTablaOriginal.setFont(font)
        self.pushButtonVerTablaOriginal.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/icons8-big-data-150.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVerTablaOriginal.setIcon(icon1)
        self.pushButtonVerTablaOriginal.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerTablaOriginal.setObjectName("pushButtonVerTablaOriginal")
        self.gridLayout.addWidget(self.pushButtonVerTablaOriginal, 20, 1, 1, 1)
        self.pushButtonGuardarImsisVSImei = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonGuardarImsisVSImei.setFont(font)
        self.pushButtonGuardarImsisVSImei.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/icons8-añadir-libro-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGuardarImsisVSImei.setIcon(icon2)
        self.pushButtonGuardarImsisVSImei.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGuardarImsisVSImei.setObjectName("pushButtonGuardarImsisVSImei")
        self.gridLayout.addWidget(self.pushButtonGuardarImsisVSImei, 24, 1, 1, 1)
        self.pushButtonVerImsisVSImeis = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonVerImsisVSImeis.setFont(font)
        self.pushButtonVerImsisVSImeis.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonVerImsisVSImeis.setIcon(icon1)
        self.pushButtonVerImsisVSImeis.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerImsisVSImeis.setObjectName("pushButtonVerImsisVSImeis")
        self.gridLayout.addWidget(self.pushButtonVerImsisVSImeis, 21, 1, 1, 1)
        self.pushButtonGuardarDatos4G = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonGuardarDatos4G.setFont(font)
        self.pushButtonGuardarDatos4G.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonGuardarDatos4G.setIcon(icon2)
        self.pushButtonGuardarDatos4G.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGuardarDatos4G.setObjectName("pushButtonGuardarDatos4G")
        self.gridLayout.addWidget(self.pushButtonGuardarDatos4G, 26, 1, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout.addWidget(self.frame, 38, 4, 1, 1)
        self.pushButtonFiltrarDatos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonFiltrarDatos.setFont(font)
        self.pushButtonFiltrarDatos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Iconos/icons8-hand-box-256.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonFiltrarDatos.setIcon(icon3)
        self.pushButtonFiltrarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonFiltrarDatos.setObjectName("pushButtonFiltrarDatos")
        self.gridLayout.addWidget(self.pushButtonFiltrarDatos, 35, 1, 1, 1)
        self.pushButtonVerDatosIncidentales = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonVerDatosIncidentales.setFont(font)
        self.pushButtonVerDatosIncidentales.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonVerDatosIncidentales.setIcon(icon1)
        self.pushButtonVerDatosIncidentales.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonVerDatosIncidentales.setObjectName("pushButtonVerDatosIncidentales")
        self.gridLayout.addWidget(self.pushButtonVerDatosIncidentales, 19, 1, 1, 1)
        self.pushButtonGuardarDatos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(10)
        self.pushButtonGuardarDatos.setFont(font)
        self.pushButtonGuardarDatos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonGuardarDatos.setIcon(icon2)
        self.pushButtonGuardarDatos.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonGuardarDatos.setObjectName("pushButtonGuardarDatos")
        self.gridLayout.addWidget(self.pushButtonGuardarDatos, 25, 1, 1, 1)
        self.tableWidgetDatosExcel = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetDatosExcel.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetDatosExcel.setObjectName("tableWidgetDatosExcel")
        self.tableWidgetDatosExcel.setColumnCount(12)
        self.tableWidgetDatosExcel.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetDatosExcel.setHorizontalHeaderItem(11, item)
        self.gridLayout.addWidget(self.tableWidgetDatosExcel, 14, 3, 25, 1)
        self.pushButtonAnalisisHorario = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonAnalisisHorario.setFont(font)
        self.pushButtonAnalisisHorario.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Iconos/icons8-tiempo-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonAnalisisHorario.setIcon(icon4)
        self.pushButtonAnalisisHorario.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonAnalisisHorario.setObjectName("pushButtonAnalisisHorario")
        self.gridLayout.addWidget(self.pushButtonAnalisisHorario, 22, 1, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.pushButtonRATS = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonRATS.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonRATS.setObjectName("pushButtonRATS")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButtonRATS)
        self.labelRATContador = QtWidgets.QLabel(self.centralwidget)
        self.labelRATContador.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelRATContador.setText("")
        self.labelRATContador.setObjectName("labelRATContador")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelRATContador)
        self.pushButtonOperadores = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonOperadores.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonOperadores.setObjectName("pushButtonOperadores")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.pushButtonOperadores)
        self.labelOperadorDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelOperadorDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelOperadorDatos.setText("")
        self.labelOperadorDatos.setObjectName("labelOperadorDatos")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelOperadorDatos)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton.setObjectName("pushButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.labelIMSIDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelIMSIDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelIMSIDatos.setText("")
        self.labelIMSIDatos.setObjectName("labelIMSIDatos")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelIMSIDatos)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.pushButton_2)
        self.labelIMEIDatos = QtWidgets.QLabel(self.centralwidget)
        self.labelIMEIDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelIMEIDatos.setText("")
        self.labelIMEIDatos.setObjectName("labelIMEIDatos")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelIMEIDatos)
        self.textEditBuscarDatos = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditBuscarDatos.sizePolicy().hasHeightForWidth())
        self.textEditBuscarDatos.setSizePolicy(sizePolicy)
        self.textEditBuscarDatos.setMaximumSize(QtCore.QSize(600, 50))
        self.textEditBuscarDatos.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.textEditBuscarDatos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditBuscarDatos.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEditBuscarDatos.setObjectName("textEditBuscarDatos")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.textEditBuscarDatos)
        self.pushButtonBuscarDato = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.pushButtonBuscarDato.setFont(font)
        self.pushButtonBuscarDato.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pushButtonBuscarDato.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0.0149254 rgba(255, 246, 85, 255), stop:1 rgba(255, 255, 255, 255));")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../../../../../.designer/backup/icons8-google-web-search-400.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonBuscarDato.setIcon(icon5)
        self.pushButtonBuscarDato.setIconSize(QtCore.QSize(40, 40))
        self.pushButtonBuscarDato.setObjectName("pushButtonBuscarDato")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pushButtonBuscarDato)
        self.gridLayout.addLayout(self.formLayout, 13, 1, 4, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/Logos/logoRaptor.png"))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 3, 1, 1)
        vistaGeneralDatos.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vistaGeneralDatos)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 26))
        self.menubar.setObjectName("menubar")
        self.menuDatos = QtWidgets.QMenu(self.menubar)
        self.menuDatos.setObjectName("menuDatos")
        vistaGeneralDatos.setMenuBar(self.menubar)
        self.actionIr_A_Principal = QtWidgets.QAction(vistaGeneralDatos)
        self.actionIr_A_Principal.setObjectName("actionIr_A_Principal")
        self.actionGuardar = QtWidgets.QAction(vistaGeneralDatos)
        self.actionGuardar.setObjectName("actionGuardar")
        self.menuDatos.addSeparator()
        self.menuDatos.addAction(self.actionIr_A_Principal)
        self.menuDatos.addAction(self.actionGuardar)
        self.menubar.addAction(self.menuDatos.menuAction())

        self.retranslateUi(vistaGeneralDatos)
        QtCore.QMetaObject.connectSlotsByName(vistaGeneralDatos)

    def retranslateUi(self, vistaGeneralDatos):
        _translate = QtCore.QCoreApplication.translate
        vistaGeneralDatos.setWindowTitle(_translate("vistaGeneralDatos", "MainWindow"))
        self.pushButtonAsignarIMEIS.setText(_translate("vistaGeneralDatos", "ASIGNAR IMEI A 4G"))
        self.pushButtonVerTablaOriginal.setText(_translate("vistaGeneralDatos", "TABLA DATOS GENERALES"))
        self.pushButtonGuardarImsisVSImei.setText(_translate("vistaGeneralDatos", "GUARDAR TABLA DATOS IMSIS VS IMEI "))
        self.pushButtonVerImsisVSImeis.setText(_translate("vistaGeneralDatos", "TABLA IMSIS VS IMEIS"))
        self.pushButtonGuardarDatos4G.setText(_translate("vistaGeneralDatos", "GUARDAR DATOS 4G"))
        self.pushButtonFiltrarDatos.setText(_translate("vistaGeneralDatos", "Filtrar Datos"))
        self.pushButtonVerDatosIncidentales.setText(_translate("vistaGeneralDatos", " TABLA DATOS INCIDENTALES"))
        self.pushButtonGuardarDatos.setText(_translate("vistaGeneralDatos", "GUARDAR TABLA (Vista Actual)"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(0)
        item.setText(_translate("vistaGeneralDatos", "RAT"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(1)
        item.setText(_translate("vistaGeneralDatos", "OPERATOR"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(2)
        item.setText(_translate("vistaGeneralDatos", "CHANNEL"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(3)
        item.setText(_translate("vistaGeneralDatos", "IMEI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(4)
        item.setText(_translate("vistaGeneralDatos", "IMSI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(5)
        item.setText(_translate("vistaGeneralDatos", "TMSI"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(6)
        item.setText(_translate("vistaGeneralDatos", "MS POWER"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(7)
        item.setText(_translate("vistaGeneralDatos", "TA"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(8)
        item.setText(_translate("vistaGeneralDatos", "LAST LAC"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(9)
        item.setText(_translate("vistaGeneralDatos", "NAME"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(10)
        item.setText(_translate("vistaGeneralDatos", "HITS"))
        item = self.tableWidgetDatosExcel.horizontalHeaderItem(11)
        item.setText(_translate("vistaGeneralDatos", "DATA-TIME"))
        self.pushButtonAnalisisHorario.setText(_translate("vistaGeneralDatos", "ANÁLISIS HORARIO DATOS GENERALES"))
        self.pushButtonRATS.setText(_translate("vistaGeneralDatos", "RAT"))
        self.pushButtonOperadores.setText(_translate("vistaGeneralDatos", "Operador"))
        self.pushButton.setText(_translate("vistaGeneralDatos", "IMSI"))
        self.pushButton_2.setText(_translate("vistaGeneralDatos", "IMEI"))
        self.pushButtonBuscarDato.setText(_translate("vistaGeneralDatos", "Buscar"))
        self.label_4.setText(_translate("vistaGeneralDatos", "<html><head/><body><p><img src=\":/Iconos/logoRaptor.png\"/></p></body></html>"))
        self.label.setText(_translate("vistaGeneralDatos", "                                                                                                                                                                        DATOS GENERALES"))
        self.menuDatos.setTitle(_translate("vistaGeneralDatos", "Datos"))
        self.actionIr_A_Principal.setText(_translate("vistaGeneralDatos", "Ir A Principal "))
        self.actionGuardar.setText(_translate("vistaGeneralDatos", "Guardar "))
# import DATOS IMAGENES_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vistaGeneralDatos = QtWidgets.QMainWindow()
    ui = Ui_vistaGeneralDatos()
    ui.setupUi(vistaGeneralDatos)
    vistaGeneralDatos.show()
    sys.exit(app.exec_())
