# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\VistaDetalleHoras.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VistaDetalleHoras(object):
    def setupUi(self, VistaDetalleHoras):
        VistaDetalleHoras.setObjectName("VistaDetalleHoras")
        VistaDetalleHoras.resize(1280, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(VistaDetalleHoras.sizePolicy().hasHeightForWidth())
        VistaDetalleHoras.setSizePolicy(sizePolicy)
        VistaDetalleHoras.setMinimumSize(QtCore.QSize(1280, 720))
        VistaDetalleHoras.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:1 rgba(85, 125, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(VistaDetalleHoras)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayoutGraficaDatosDinamicos = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraficaDatosDinamicos.setObjectName("verticalLayoutGraficaDatosDinamicos")
        self.gridLayout_8.addLayout(self.verticalLayoutGraficaDatosDinamicos, 6, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_8.addWidget(self.label_7, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.dateTimeEditIngresoFinal = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditIngresoFinal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateTimeEditIngresoFinal.setObjectName("dateTimeEditIngresoFinal")
        self.gridLayout.addWidget(self.dateTimeEditIngresoFinal, 3, 1, 1, 1)
        self.dateTimeEditIngresoInicial = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEditIngresoInicial.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateTimeEditIngresoInicial.setObjectName("dateTimeEditIngresoInicial")
        self.gridLayout.addWidget(self.dateTimeEditIngresoInicial, 3, 0, 1, 1)
        self.tableWidgetMostrarDatosFiltrados = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetMostrarDatosFiltrados.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetMostrarDatosFiltrados.setObjectName("tableWidgetMostrarDatosFiltrados")
        self.tableWidgetMostrarDatosFiltrados.setColumnCount(3)
        self.tableWidgetMostrarDatosFiltrados.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosFiltrados.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosFiltrados.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosFiltrados.setHorizontalHeaderItem(2, item)
        self.gridLayout.addWidget(self.tableWidgetMostrarDatosFiltrados, 8, 0, 1, 2)
        self.pushButtonVerDatosTablaFiltrada = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonVerDatosTablaFiltrada.sizePolicy().hasHeightForWidth())
        self.pushButtonVerDatosTablaFiltrada.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonVerDatosTablaFiltrada.setFont(font)
        self.pushButtonVerDatosTablaFiltrada.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Recursos/icons8-ver-80.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonVerDatosTablaFiltrada.setIcon(icon)
        self.pushButtonVerDatosTablaFiltrada.setIconSize(QtCore.QSize(30, 40))
        self.pushButtonVerDatosTablaFiltrada.setObjectName("pushButtonVerDatosTablaFiltrada")
        self.gridLayout.addWidget(self.pushButtonVerDatosTablaFiltrada, 6, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.pushButtonaGuardarBusquedaTabla1 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonaGuardarBusquedaTabla1.sizePolicy().hasHeightForWidth())
        self.pushButtonaGuardarBusquedaTabla1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonaGuardarBusquedaTabla1.setFont(font)
        self.pushButtonaGuardarBusquedaTabla1.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons8-añadir-libro-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonaGuardarBusquedaTabla1.setIcon(icon1)
        self.pushButtonaGuardarBusquedaTabla1.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonaGuardarBusquedaTabla1.setObjectName("pushButtonaGuardarBusquedaTabla1")
        self.gridLayout.addWidget(self.pushButtonaGuardarBusquedaTabla1, 6, 1, 1, 1)
        self.pushButtonGraficarDatosTablaFiltrada = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonGraficarDatosTablaFiltrada.setFont(font)
        self.pushButtonGraficarDatosTablaFiltrada.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Recursos/20803.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonGraficarDatosTablaFiltrada.setIcon(icon2)
        self.pushButtonGraficarDatosTablaFiltrada.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonGraficarDatosTablaFiltrada.setObjectName("pushButtonGraficarDatosTablaFiltrada")
        self.gridLayout.addWidget(self.pushButtonGraficarDatosTablaFiltrada, 10, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_6, 2, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonGraficarDatosEstaticos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonGraficarDatosEstaticos.setFont(font)
        self.pushButtonGraficarDatosEstaticos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonGraficarDatosEstaticos.setIcon(icon2)
        self.pushButtonGraficarDatosEstaticos.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonGraficarDatosEstaticos.setObjectName("pushButtonGraficarDatosEstaticos")
        self.gridLayout_3.addWidget(self.pushButtonGraficarDatosEstaticos, 17, 1, 1, 1)
        self.comboBoxVerMayorMenor = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxVerMayorMenor.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxVerMayorMenor.setObjectName("comboBoxVerMayorMenor")
        self.comboBoxVerMayorMenor.addItem("")
        self.comboBoxVerMayorMenor.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxVerMayorMenor, 5, 0, 1, 1)
        self.pushButtonGuardarBsuquedaTabla2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonGuardarBsuquedaTabla2.setFont(font)
        self.pushButtonGuardarBsuquedaTabla2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonGuardarBsuquedaTabla2.setIcon(icon1)
        self.pushButtonGuardarBsuquedaTabla2.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonGuardarBsuquedaTabla2.setObjectName("pushButtonGuardarBsuquedaTabla2")
        self.gridLayout_3.addWidget(self.pushButtonGuardarBsuquedaTabla2, 7, 1, 1, 1)
        self.tableWidgetMostrarDatosEstaticos = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetMostrarDatosEstaticos.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetMostrarDatosEstaticos.setObjectName("tableWidgetMostrarDatosEstaticos")
        self.tableWidgetMostrarDatosEstaticos.setColumnCount(3)
        self.tableWidgetMostrarDatosEstaticos.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosEstaticos.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosEstaticos.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetMostrarDatosEstaticos.setHorizontalHeaderItem(2, item)
        self.gridLayout_3.addWidget(self.tableWidgetMostrarDatosEstaticos, 15, 1, 1, 1)
        self.comboBoxOrganizacionJornadas = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBoxOrganizacionJornadas.sizePolicy().hasHeightForWidth())
        self.comboBoxOrganizacionJornadas.setSizePolicy(sizePolicy)
        self.comboBoxOrganizacionJornadas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBoxOrganizacionJornadas.setObjectName("comboBoxOrganizacionJornadas")
        self.comboBoxOrganizacionJornadas.addItem("")
        self.comboBoxOrganizacionJornadas.addItem("")
        self.comboBoxOrganizacionJornadas.addItem("")
        self.comboBoxOrganizacionJornadas.addItem("")
        self.comboBoxOrganizacionJornadas.addItem("")
        self.gridLayout_3.addWidget(self.comboBoxOrganizacionJornadas, 5, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.textEditValorFiltro = QtWidgets.QTextEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEditValorFiltro.sizePolicy().hasHeightForWidth())
        self.textEditValorFiltro.setSizePolicy(sizePolicy)
        self.textEditValorFiltro.setMaximumSize(QtCore.QSize(16777215, 30))
        self.textEditValorFiltro.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.textEditValorFiltro.setObjectName("textEditValorFiltro")
        self.gridLayout_3.addWidget(self.textEditValorFiltro, 0, 1, 1, 1)
        self.pushButtonVerDatosEstaticos = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Corbel")
        font.setPointSize(12)
        self.pushButtonVerDatosEstaticos.setFont(font)
        self.pushButtonVerDatosEstaticos.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(63, 117, 194, 200), stop:1 rgba(255, 255, 255, 255));")
        self.pushButtonVerDatosEstaticos.setIcon(icon)
        self.pushButtonVerDatosEstaticos.setIconSize(QtCore.QSize(30, 30))
        self.pushButtonVerDatosEstaticos.setObjectName("pushButtonVerDatosEstaticos")
        self.gridLayout_3.addWidget(self.pushButtonVerDatosEstaticos, 6, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 3, 1, 1, 1)
        self.verticalLayoutGraficosDatosEstaticos = QtWidgets.QVBoxLayout()
        self.verticalLayoutGraficosDatosEstaticos.setObjectName("verticalLayoutGraficosDatosEstaticos")
        self.gridLayout_8.addLayout(self.verticalLayoutGraficosDatosEstaticos, 8, 2, 1, 1)
        VistaDetalleHoras.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(VistaDetalleHoras)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuVolver = QtWidgets.QMenu(self.menubar)
        self.menuVolver.setObjectName("menuVolver")
        VistaDetalleHoras.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(VistaDetalleHoras)
        self.statusbar.setObjectName("statusbar")
        VistaDetalleHoras.setStatusBar(self.statusbar)
        self.actionVolverDatos_General = QtWidgets.QAction(VistaDetalleHoras)
        self.actionVolverDatos_General.setObjectName("actionVolverDatos_General")
        self.menuVolver.addAction(self.actionVolverDatos_General)
        self.menubar.addAction(self.menuVolver.menuAction())

        self.retranslateUi(VistaDetalleHoras)
        QtCore.QMetaObject.connectSlotsByName(VistaDetalleHoras)

    def retranslateUi(self, VistaDetalleHoras):
        _translate = QtCore.QCoreApplication.translate
        VistaDetalleHoras.setWindowTitle(_translate("VistaDetalleHoras", "MainWindow"))
        self.label_7.setText(_translate("VistaDetalleHoras", "LISTA FILTRAR DATOS"))
        item = self.tableWidgetMostrarDatosFiltrados.horizontalHeaderItem(0)
        item.setText(_translate("VistaDetalleHoras", "IMEI"))
        item = self.tableWidgetMostrarDatosFiltrados.horizontalHeaderItem(1)
        item.setText(_translate("VistaDetalleHoras", "IMSIS"))
        item = self.tableWidgetMostrarDatosFiltrados.horizontalHeaderItem(2)
        item.setText(_translate("VistaDetalleHoras", "Data-Time"))
        self.pushButtonVerDatosTablaFiltrada.setText(_translate("VistaDetalleHoras", "Filtrar Datos y Ver (Tabla 1)"))
        self.label_6.setText(_translate("VistaDetalleHoras", "Desde"))
        self.label_5.setText(_translate("VistaDetalleHoras", "   Hasta"))
        self.pushButtonaGuardarBusquedaTabla1.setText(_translate("VistaDetalleHoras", "Guardar Busqueda (Tabla 1)"))
        self.pushButtonGraficarDatosTablaFiltrada.setText(_translate("VistaDetalleHoras", "Graficar Datos De Tabla 1"))
        self.pushButtonGraficarDatosEstaticos.setText(_translate("VistaDetalleHoras", "Graficar Datos De Tabla 2"))
        self.comboBoxVerMayorMenor.setItemText(0, _translate("VistaDetalleHoras", "Mayor"))
        self.comboBoxVerMayorMenor.setItemText(1, _translate("VistaDetalleHoras", "Menor"))
        self.pushButtonGuardarBsuquedaTabla2.setText(_translate("VistaDetalleHoras", "Guardar Busqueda (Tabla 2)"))
        item = self.tableWidgetMostrarDatosEstaticos.horizontalHeaderItem(0)
        item.setText(_translate("VistaDetalleHoras", "IMEI"))
        item = self.tableWidgetMostrarDatosEstaticos.horizontalHeaderItem(1)
        item.setText(_translate("VistaDetalleHoras", "IMSI"))
        item = self.tableWidgetMostrarDatosEstaticos.horizontalHeaderItem(2)
        item.setText(_translate("VistaDetalleHoras", "DATA-TIME"))
        self.comboBoxOrganizacionJornadas.setItemText(0, _translate("VistaDetalleHoras", "Ver Datos Agrupados"))
        self.comboBoxOrganizacionJornadas.setItemText(1, _translate("VistaDetalleHoras", "Uso Durante Madrugada (00:00:00 am - 05:59:59 am)"))
        self.comboBoxOrganizacionJornadas.setItemText(2, _translate("VistaDetalleHoras", "Uso Durante Mañana (06:00:00 am - 11:59:59 pm)"))
        self.comboBoxOrganizacionJornadas.setItemText(3, _translate("VistaDetalleHoras", "Uso Durante Tarde (12:00:00 pm - 18:59:59 pm)"))
        self.comboBoxOrganizacionJornadas.setItemText(4, _translate("VistaDetalleHoras", "Uso Durante Noche (19:00:00 pm - 23:59:59 pm)"))
        self.label.setText(_translate("VistaDetalleHoras", "Ingresar Valor delimitador"))
        self.pushButtonVerDatosEstaticos.setText(_translate("VistaDetalleHoras", "Filtrar Datos y Ver (Tabla 2)"))
        self.menuVolver.setTitle(_translate("VistaDetalleHoras", "Volver"))
        self.actionVolverDatos_General.setText(_translate("VistaDetalleHoras", "Datos General"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VistaDetalleHoras = QtWidgets.QMainWindow()
    ui = Ui_VistaDetalleHoras()
    ui.setupUi(VistaDetalleHoras)
    VistaDetalleHoras.show()
    sys.exit(app.exec_())
